### ISSUE TITLE
Redis-cli container close just after start

### ISSUE THREAD

**Issue by alessandromr** [FabrizioCafolla/microservice-lumen#5]
Redis-cli container close just after start, logs seems to be empty.
Problem seems to be related to `command` attribute on docker-compose.

``` 
  # Use it with command: docker-compose run redis-cli
  redis-cli:
    container_name: ${NAME}_redis-cli
    image: "${REDIS_NAME}:${REDIS_TAG}"
    links:
      - redis
    command: redis-cli -h redis
```
